READY = "READY";
APPLICATION_COMMAND_UPDATE = "APPLICATION_COMMAND_UPDATE";
INTERACTION_CREATE = "INTERACTION_CREATE";

module.exports = {
    READY,
    INTERACTION_CREATE,
    APPLICATION_COMMAND_UPDATE
};