DISPATCH = 0;
HEARTBEAT = 1;
IDENTIFY = 2;
PRESENCEUPDATE = 3;
VOICESTATUSUPDATE = 4;
RESUME = 6;
RECONNECT = 7;
REQUESTGUILDMEMBERS = 8;
INVALIDSESSION = 9;
HELLO = 10;
HEARTBEATACK = 11;

module.exports = { 
    DISPATCH, 
    HEARTBEAT, 
    IDENTIFY, 
    PRESENCEUPDATE, 
    VOICESTATUSUPDATE, 
    RESUME, 
    RECONNECT, 
    REQUESTGUILDMEMBERS, 
    INVALIDSESSION, 
    HELLO, 
    HEARTBEATACK 
};